### ISSUE TITLE
 Value passed to parameter 'input_sizes' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by Julius-ZCJ** [EdwardSmith1884/3D-IWGAN#27]
When I run you item, I get this error.

Traceback (most recent call last):
  File "E:/GAN/7-3D-IWGAN-master/3D-IWGAN-master/3D-Generation/32-3D-Gan.py", line 49, in <module>
    net_g , G_train     = generator_32(z, is_train=True, reuse = False, sig= True, batch_size=args.batchsize)
  File "E:\GAN\7-3D-IWGAN-master\3D-IWGAN-master\scripts\models.py", line 74, in generator_32
    net_2 = Deconv(net_1, gf_dim, eighth, '2', batch_size) 
  File "E:\GAN\7-3D-IWGAN-master\3D-IWGAN-master\scripts\models.py", line 20, in Deconv
    act=tf.identity, name='g/net_' + net + '/deconv')
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorlayer\layers.py", line 1512, in __init__
    self.outputs = act( tf.nn.conv3d_transpose(self.inputs, W, output_shape=output_shape, strides=strides, padding=padding) + b )
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2473, in conv3d_transpose
    name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2539, in conv3d_transpose_v2
    name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 2237, in conv3d_backprop_input_v2
    dilations=dilations, name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 627, in _apply_op_helper
    param_name=input_name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input_sizes' has DataType float32 not in list of allowed values: int32, int64

I find this error raise becaues 'Conv3DBackpropInputV2' not has float32 dtype, I don't konw why.
Do you have some ideas for this error.

By the why, what tensorflow and tensorlayer version do you used?

**Comment by EdwardSmith1884** [comment]
Hi, try tensorflow==1.13.2 and tensorlayer==1.5.0

**Comment by Yucitrus** [comment]
> Hi, try tensorflow==1.13.2 and tensorlayer==1.5.0

After replacing with tensorflow==1.13.2 and tensorlayer==1.5.0, the error still exists. Is there any other solution?

**Comment by EdwardSmith1884** [comment]
Hi, which python version are you using?

**Comment by EfreetWarfarin** [comment]
Hi,I found that the issue is in the `Deconv` function in `./scripts/models.py`, where the `out_shape` should be of type `int` instead of `float`. So I modified it like this:

```python
def Deconv(inputs, f_dim_in, dim, net, batch_size, f_dim_out=None, stride=2):
    if f_dim_out is None: 
        f_dim_out = f_dim_in / 2 
    output_shape = [batch_size, dim, dim, dim, f_dim_out]
    output_shape = tf.cast(output_shape, tf.int32)  
    return tl.layers.DeConv3dLayer(inputs,
                                   shape=[4, 4, 4, f_dim_out, f_dim_in],
                                   output_shape=output_shape,
                                   strides=[1, stride, stride, stride, 1],
                                   W_init=tf.random_normal_initializer(stddev=0.02),
                                   act=tf.identity, name='g/net_' + net + '/deconv')
```

But this might not be the best solution, as it could lose some precision.

----------------

我发现问题出在`./scripts/models.py`中的`Deconv`函数，`out_shape`应该是`int`类型而不是`float`类型。因此，我做了如下修改：

```python
def Deconv(inputs, f_dim_in, dim, net, batch_size, f_dim_out=None, stride=2):
    if f_dim_out is None: 
        f_dim_out = f_dim_in / 2 
    output_shape = [batch_size, dim, dim, dim, f_dim_out]
    output_shape = tf.cast(output_shape, tf.int32)  
    return tl.layers.DeConv3dLayer(inputs,
                                   shape=[4, 4, 4, f_dim_out, f_dim_in],
                                   output_shape=output_shape,
                                   strides=[1, stride, stride, stride, 1],
                                   W_init=tf.random_normal_initializer(stddev=0.02),
                                   act=tf.identity, name='g/net_' + net + '/deconv')
```

但这可能不是最好的解决办法，因为可能会丧失精度。
